name: Generate Codebase Summary

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'app.py'
      - 'modules/**.py'
      - 'generate_code_summary.py'
      - '.github/workflows/generate_summary.yml'
  workflow_dispatch:

jobs:
  generate-summary:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Run summary generator script
        run: python generate_code_summary.py

      - name: Commit and push if summary changed
        run: |
          echo "--- Checking Git status before add ---"
          git status # Show status before adding
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add codebase_summary.md
          echo "--- Checking Git status after add ---"
          git status # Show status after adding
          if ! git diff --staged --quiet; then
            echo "Changes detected in codebase_summary.md. Attempting to commit..."
            git commit -m "Automated: Update codebase_summary.md"
            echo "Commit successful. Attempting to push..."
            git push
            echo "codebase_summary.md was updated and pushed."
          else
            echo "No changes to codebase_summary.md. Nothing to commit."
          fi
